### ISSUE TITLE
Curios is unable to refuel Jetpack slot

### ISSUE THREAD

**Issue by NgLoader** [GoryMoon/Chargers#22]
You just need to put your jetpack into the curios jetpack slot and you will see that the jetpack is not loading.

<details>
  <summary>Config</summary>
 
  ```toml
#Common configs
[common]

	#Compat configs
	[common.compat]
		#If curios compat should be enabled
		curios_compat = true
  ```
</details>

<details>
  <summary>Server config</summary>
 
  ```toml
#Chargers configs
[chargers]

	[chargers.tier_1]
		#The amount of energy the charger can hold
		#Range: > 0
		storage = 25000
		#The amount of energy/tick that can be inserted
		#Range: > 0
		max_input = 500
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		#Range: > 0
		max_output = 500

	[chargers.tier_2]
		#The amount of energy the charger can hold
		#Range: > 0
		storage = 500000
		#The amount of energy/tick that can be inserted
		#Range: > 0
		max_input = 10000
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		#Range: > 0
		max_output = 10000

	[chargers.tier_3]
		#The amount of energy the charger can hold
		#Range: > 0
		storage = 1000000
		#The amount of energy/tick that can be inserted
		#Range: > 0
		max_input = 25000
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		#Range: > 0
		max_output = 25000

	[chargers.tier_4]
		#The amount of energy the charger can hold
		#Range: > 0
		storage = 25000000
		#The amount of energy/tick that can be inserted
		#Range: > 0
		max_input = 625000
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		#Range: > 0
		max_output = 625000

	[chargers.wireless]
		#The amount of energy the wireless charger can hold
		#Range: > 0
		storage = 200000
		#The amount of energy/tick that can be inserted
		#Range: > 0
		max_input = 4000
		#The amount of energy/tick that can be extracted
		#This is the max speed items would be charged at, actual speed could be slower depending on item
		#Range: > 0
		max_output = 4000
		#The range from the charger that item will be charged
		#Range: 0 ~ 128
		range = 24
  ```
</details>

Mod version:
- SimplyJetpacks2: SimplyJetpacks2-1.18.2-2.8.0.1.jar : simplyjetpacks (1.18.2-2.8.0.1) 
- Curios: curios-forge-1.18.2-5.0.7.1.jar : curios (1.18.2-5.0.7.1)
- Chargers: Chargers-1.18.2-4.2.1.14.jar : chargers (4.2.1.14) 
- Forge: forge-1.18.2-40.1.73-universal.jar : forge (40.1.73)
- Minecraft: server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2)
